package com.hhb.app.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import com.hhb.app.dto.BookCount;
import com.hhb.app.entil.Book;

public interface BookMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbggenerated Fri Jan 29 11:22:28 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbggenerated Fri Jan 29 11:22:28 CST 2016
     */
    int insert(Book record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbggenerated Fri Jan 29 11:22:28 CST 2016
     */
    int insertSelective(Book record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbggenerated Fri Jan 29 11:22:28 CST 2016
     */
    Book selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbggenerated Fri Jan 29 11:22:28 CST 2016
     */
    int updateByPrimaryKeySelective(Book record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbggenerated Fri Jan 29 11:22:28 CST 2016
     */
    int updateByPrimaryKey(Book record);
    
    List<Book> selectByBookName(@Param("bookName")String bookName, RowBounds rowBounds);
    
    BookCount selectCount(@Param("bookName")String bookName, RowBounds rowBounds);
}